# Generated by Django 5.2.11 on 2026-02-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=80)),
                ('whatsapp_number', models.CharField(help_text='Use dolo digitos, incluya prefijo internacional. Ejemplo: 573001234567', max_length=20)),
                ('instagram_handle', models.CharField(max_length=50)),
                ('approved', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('price', models.PositiveIntegerField(help_text='Precio en pesos colombianos, no puntos/comas')),
                ('size', models.CharField(help_text='Ejemplo: S, M, L, 28, 40, Única', max_length=20)),
                ('category', models.CharField(choices=[('tops', 'Tops'), ('bottoms', 'Bottoms'), ('dresses', 'Dresses'), ('outerwear', 'Outerwear'), ('shoes', 'Shoes'), ('accessories', 'Accessories'), ('other', 'Other')], default='other', max_length=20)),
                ('condition', models.CharField(choices=[('new', 'New'), ('like_new', 'Like new'), ('good', 'Good'), ('fair', 'Fair')], default='good', max_length=20)),
                ('photo', models.ImageField(upload_to='items/')),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='market.store')),
            ],
        ),
    ]
