# Generated by Django 5.2.11 on 2026-02-18 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='whatsapp_clicks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('tops', 'Blusas / Tops'), ('bottoms', 'Pantalones / Faldas'), ('dresses', 'Vestidos'), ('outerwear', 'Chaquetas / Abrigos'), ('shoes', 'Zapatos'), ('accessories', 'Accesorios'), ('other', 'Otro')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('new', 'Nuevo'), ('like_new', 'Como nuevo'), ('good', 'Buena'), ('fair', 'Aceptable')], default='good', max_length=20),
        ),
    ]
