# Generated by Django 5.2.11 on 2026-03-04 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='name',
        ),
    ]
