# Generated by Django 5.2.11 on 2026-04-08 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_itemimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='stores/'),
        ),
    ]
